version: '3.8'

services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    restart: always
    ports:
        - 5672:5672
        - 15672:15672